-- Create HOTEL table
CREATE TABLE IF NOT EXISTS HOTEL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Insert sample data into HOTEL
INSERT INTO HOTEL (NAME) VALUES ('Grand Hotel');
INSERT INTO HOTEL (NAME) VALUES ('Seaside Resort');
INSERT INTO HOTEL (NAME) VALUES ('Mountain Inn');

-- Create ROOM table (with a foreign key to HOTEL)
CREATE TABLE IF NOT EXISTS ROOM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_NUMBER VARCHAR(255) NOT NULL,
    ROOM_TYPE VARCHAR(255) NOT NULL,
    HOTEL_ID BIGINT NOT NULL,
    FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(ID) ON DELETE CASCADE
);

-- Insert sample data into ROOM
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, HOTEL_ID) VALUES ('101', 'Single', 1);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, HOTEL_ID) VALUES ('102', 'Double', 1);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, HOTEL_ID) VALUES ('201', 'Suite', 2);
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE, HOTEL_ID) VALUES ('202', 'Single', 3);

-- Create CUSTOMER table (quoted as "CUSTOMER")
CREATE TABLE IF NOT EXISTS "CUSTOMER" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

-- Insert sample data into CUSTOMER
INSERT INTO "CUSTOMER" (NAME, EMAIL) VALUES ('John Doe', 'john.doe@example.com');
INSERT INTO "CUSTOMER" (NAME, EMAIL) VALUES ('Jane Smith', 'jane.smith@example.com');
INSERT INTO "CUSTOMER" (NAME, EMAIL) VALUES ('Alice Johnson', 'alice.johnson@example.com');
INSERT INTO "CUSTOMER" (NAME, EMAIL) VALUES ('Bob Brown', 'bob.brown@example.com');
INSERT INTO "CUSTOMER" (NAME, EMAIL) VALUES ('Charlie Davis', 'charlie.davis@example.com');

-- Create BOOKING table (foreign keys to CUSTOMER and ROOM)
CREATE TABLE IF NOT EXISTS "BOOKING" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ROOM_ID BIGINT NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    CHECK_OUT_DATE DATE NOT NULL,
    IS_CANCELLED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES "CUSTOMER"(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID) ON DELETE CASCADE
);

-- Insert sample data into BOOKING
INSERT INTO "BOOKING" (CUSTOMER_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, IS_CANCELLED)
VALUES (1, 1, '2025-01-21', '2025-01-22', FALSE);

INSERT INTO "BOOKING" (CUSTOMER_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, IS_CANCELLED)
VALUES (2, 3, '2025-02-01', '2025-02-05', FALSE);

INSERT INTO "BOOKING" (CUSTOMER_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, IS_CANCELLED)
VALUES (3, 2, '2025-01-23', '2025-01-25', TRUE);

INSERT INTO "BOOKING" (CUSTOMER_ID, ROOM_ID, CHECK_IN_DATE, CHECK_OUT_DATE, IS_CANCELLED)
VALUES (4, 4, '2025-03-10', '2025-03-15', FALSE);
